#
# Module manifest for module 'PSPsat'
#
# Generated by: regg00@gmail.com
#
# Generated on: 2023-07-10
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'PSPsat.psm1'

    # Version number of this module.
    ModuleVersion     = '0.0.8'    

    # ID used to uniquely identify this module
    GUID              = 'cd09f0fe-045e-4b64-b20f-15296fb6a475'

    # Author of this module
    Author            = 'regg00@gmail.com'

    # Company or vendor of this module
    CompanyName       = 'Unknown'

    # Copyright statement for this module
    Copyright         = '(c) regg00. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'A PowerShell module to interact with the Proofpoint Security Awareness Training reporting API.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '3.0'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('Get-PsatUsers', 'Connect-Psat', 'Get-PsatPhishing', 'Get-PsatPhishAlarm', 'Get-PsatKnowledgeAssessment', 'Get-PsatTraining')

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # List of all files packaged with this module
    FileList          = @('PSPsat.psd1', 'PSPsat.psm1')

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags                     = @('proofpoint', 'psat', 'security', 'awareness', 'training')

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            ProjectUri               = 'https://github.com/regg00/PowerShell-PSAT'

            # A URL to an icon representing this module.
            IconUri                  = 'https://raw.githubusercontent.com/regg00/PowerShell-PSAT/main/docs/pp-logo.png'

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI       = 'https://github.com/regg00/PowerShell-PSAT'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

