name: Publish to PowerShell Gallery

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Perform Pester tests
        shell: pwsh
        run: |
          Invoke-Pester Tests\PSPsat.Tests.ps1 -Passthru

  checkout-and-publish:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Publish module
        uses: natescherer/publish-powershell-action@v1.0.3
        with:
          token: ${{ secrets.PS_GALLERY_KEY }}
          target: gallery
          path: .
