name: Publish to PowerShell Gallery

on:
  release: 
    types: [published]
  workflow_dispatch:
  
jobs:
  checkout-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3              
      
      - name: Publish module
        uses: natescherer/publish-powershell-action@v1.0.3
        with:
          token: ${{ secrets.PS_GALLERY_KEY }}
          target: gallery
          path: .

      
